### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by wdjacca** [amayadwillis/DisneySongs#3]
Webpages
Ask Dr. B about xsd:id
Ask Dr. B about what to do with the directory

**Comment by wdjacca** [comment]
associate schematron and double check

**Comment by wdjacca** [comment]
finish master song list and find words that repeat the most for SVG
flesh us the website somehow
number of words in each song, most frequent words, number of unique words, voyant

**Comment by amayadwillis** [comment]
Some ideas to work on this semester:

- consider layout -> should we create separate dropdown menus for each franchise OR just add new franchises onto existing tabs?
- find the ratio of how many times characters get singing parts
- screen time for character songs?
- compare franchises individually and/or against each other 
- more interactive graphs and decorations
- fix broken visualizations
- update about the project to tie in this year as well
- reconsider the main page to fit multiple movies
- creat biographies for voice actors/lyricists/composers etc (to track their movies and songs?)
- Add synopsis for the movies/franchises

**Comment by wdjacca** [comment]
- [ ] update Git Hub pages to match newtfire
- [ ] complete personography lists
- [ ] highlight lyrics

**Comment by amayadwillis** [comment]
- [ ] replace aladdin.html with the new php
-> Make the index page links go to aladdinMovie.php and bnbMovie.php instead of aladdin.html and bnb.html

- [ ] add css to the php pages
-> make the iframe and the song titles side by side rather than in a vertical line
-> make the numbers look nicer?
-> consider link colors

- [ ] remove javascript toggle lines from files and put them in in their own file -> use serverside include to add to files
-> make sure the code for the highlight box is showing up 
                   [EDIT: I got the JavaScript working on the iframes now :D]

- [ ] figure out how to tag the ngrams in the XML so we can capture them using the xslt?

- [ ] make sure there are XML files for all bnb songs (I think I forgot a couple when I originally did them?) 
                  EDIT: added XML for the songs I missed and fixed some inconsistencies]

**Comment by amayadwillis** [comment]
UPDATE PERSONOGRAPHY (for java script reasons)

Beauty and the Beast:

#Mrs. Potts -> #Potts
#Plumette -> #Fifif
#Armoire -> #Wardrobe
#Chorus -> either #Castleware or #Townies

add #Maurice
add #Cadenza

Aladdin:

add #Sultan
add #Peddler

remove #Both
